sources:
  npm: true
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
reviewed:
  npm:
    - faye-websocket
    - fs.realpath
    - glob
    - google-gax
    - hash-stream-validation
    - http-parser-js
    - ieee754
    - lodash.at
    - lodash.camelcase
    - lodash.defaults
    - lodash.difference
    - lodash.flatten
    - lodash.has
    - lodash.includes
    - lodash.isboolean
    - typedarray
    - websocket-driver
    - websocket-extensions
